BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        id: name_label_boxes
#    Label:
#        size_hint_y: 0.1
        text: app.status_text
#    BoxLayout:
#        orientation: 'vertical'
#        size_hint_y: 0.2
#        Button:
#            text: "Create widgets"
#            on_release: app.create_widgets()
#        Button:
#            text: "Clear widgets"
#            on_release: app.clear_all()